name: Release pipeline
on: 
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

# date +"%3N"
#startTimeInMillis

env:
  NEW_RELEASE_VERSION: v1
#   RUN_ID: "${{ github.run_attempt }}"
#   AWS_GITHUB_ROLE: test-lannisters-prod
#   AWS_ACCOUNT_ID: 165908609791

jobs:
  test:
    name: run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          cache: 'gradle'
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.15.1' # The Go version to download (if necessary) and use.
      - run: go version
      - name: Go test
        run: go build -o sshaws cmd/sshaws/main.go
      - name: Go test
        run: GOOS=darwin GOARCH=amd64 go build -o sshaws.mac cmd/sshaws/main.go
      - name: Go test
        run: GOOS=windows GOARCH=amd64 go build -o sshaws.win cmd/sshaws/main.go
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.NEW_RELEASE_VERSION }}
          release_name: "Release${{ env.NEW_RELEASE_VERSION }}""
          body: |
            Changes in this Release
            - Add support for bastion hosts on Ubuntu 22.04, where RSA is disabled.
          draft: false
          prerelease: false
