name: Release pipeline
on: 
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          cache: 'gradle'
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.15.1' # The Go version to download (if necessary) and use.
      - run: go version
      - name: Go test
        run: go build -o bin/sshaws cmd/sshaws/main.go
      - name: Go test
        run: GOOS=darwin GOARCH=amd64 go build -o bin/sshaws.mac cmd/sshaws/main.go
      - name: Go test
        run: GOOS=windows GOARCH=amd64 go build -o bin/sshaws.win cmd/sshaws/main.go
      - uses: actions/upload-artifact@v3
        with:
          name: upload-binary-artifacts
          path: |
            bin
